### ISSUE TITLE
[tracker] Start plan-only mode for Terraform CR when creating a new branch on GitHub

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#576]
### User story

As a developer, I want to be able to create a new branch and make changes to the Terraform configuration files in a "plan-only" mode so that I can review the plan information before merging the changes into the main branch.

### Subtasks:
 - [x] #577
 - [x] #578
 - [x] #580
 - [x] #581
 - [x] #582
 - [x] #583
 - [x] #605
 - [x] #588
 - [x] #628
 - [x] #670
 - [x] #661
 - [x] #662 X
 - [x] #663
 - [x] #586
 - [x] #664 X
 - [x] #669
 - [x] #665

### Acceptance criteria:
- [x] Successfully implement a feature flag for the branch-based planner system, allowing it to be toggled on or off.
- [x] Establish a clear communication mechanism between GitHub and the planner system, ensuring seamless integration.
- [x] Look at your information (PRs).
- [x] Design and create a mini controller capable of creating Terraform CR and its sourceRef for the planning mode by talking the K8s API server
- [x] Watching comments, enabling the correct triggering of actions based on the command in a comment.
- [ ] Develop and execute a comprehensive testing strategy to validate end-to-end communication between GitHub, the hook receiver, the mini controller, and the K8s API server, ensuring the functionality meets the desired requirements.
- [ ] User guide & documentations

### Success metric:
- [ ] Get feedback from one customer or prospect

**Comment by chanwit** [comment]
ping @yitsushi @yiannistri

**Comment by LappleApple** [comment]
Intermediary step: post in our Slack channel to drive feedback

Next step/milestone: Support more git providers, starting with GitLab with Azure DevOps

**Comment by chanwit** [comment]
https://github.com/weaveworks/tf-controller/issues/691
