### ISSUE TITLE
[umbrella ticket] Improve Terraform resource deletion mechanism

### ISSUE THREAD

**Issue by chanwit** [weaveworks/tf-controller#755]
This is the umbrella ticket for label: https://github.com/weaveworks/tf-controller/labels/area%2Fresource-deletion

**User Story:**

As a Terraform Controller user, 
I'd like to have a reliable Terraform resource deletion mechanism, 
so that managing the deletion process of my resources becomes more efficient. 

Fixing these problems will improve controller architecture Issues belong to three sub-groups, sequenced in order of our work plan:

**Single resource deletion**
- [ ] #632
- [ ] #454 
- [x] #666

**Resources with dependency deletion**
- [ ] #747 
- [ ] #720
- [ ] #1019

**Namespace deletion (most difficult)**
- [ ] #706 
- [x] #641 
- [ ] #584 

**Optional**
- [ ] #456

**Acceptance Criteria:**
- [ ] **Single resource deletion:** Improve the reliability of Terraform resource deletion process, using [X] as a metric.
- [ ] **Resource deletion with dependencies:** Ensure reliable handling of dependent resources during deletion, using [X] as a metric.
- [ ] **Namespace deletion:** Ensure reliable handling of deletion of the whole namespace, using [X] as a metric.
- [ ] Provide informative error messages for resource deletion failures
- [ ] Develop comprehensive documentation on the improved deletion mechanism
- [ ] Testing is added
- [ ] Address all of the issues listed above
