### ISSUE TITLE
[Umbrella] Meet the OpenSSF's best practices reqts for the "Passing" badge

### ISSUE THREAD

**Issue by LappleApple** [weaveworks/tf-controller#859]
Many OSS projects, including Flagger and Flux, apply the Open Source Security Foundation (OpenSSF)'s [best practices](https://bestpractices.coreinfrastructure.org/en/criteria/0) to gain/retain user trust and as part of their project governance activities. 

**TODOs:**
- [x] Do spike to document which criteria TF Controller already fulfills
- [x] Application filed using generic bot email for team
- [x] Add badge to Readme: [![OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/projects/7761/badge)](https://bestpractices.coreinfrastructure.org/projects/7761); #892 
- [x] Create security.md for TF Controller with details for users to submit vulnerability info/reports. (See [Flagger example](https://github.com/fluxcd/flagger/security/policy))
- [x] Test suite to cover most (or ideally all) the code branches, input fields, and functionality.
- [x] Add linter ("The project MUST enable one or more compiler warning flags, a "safe" language mode, or use a separate "linter" tool to look for code quality errors or common simple mistakes, if there is at least one FLOSS tool that can implement this criterion in the selected language.")
- [x] The project MUST address warnings (applying linter would take care of this)
- [ ] use a configuration for at least some dynamic analysis (such as testing or fuzzing) which enables many assertions. In many cases these assertions should not be enabled in production builds. ("This criterion does not suggest enabling assertions during production; that is entirely up to the project and its users to decide. This criterion's focus is instead to improve fault detection during dynamic analysis before deployment.")

AC: Receive the [Passing badge](https://bestpractices.coreinfrastructure.org/en/criteria/0). 

To discuss: whether we want to make fulfillment of these reqts a condition of the v0.16.0 release. Will need to assess required effort.

**Comment by LappleApple** [comment]
One story: Run the tool to find gaps and turn them into stories

**Comment by yiannistri** [comment]
We have now received the OpenSSF best practices Passing badge.
